# Generated by Django 5.2 on 2025-05-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intellishop", "0002_alter_user_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
